name: Fetch Article Content

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install uv
          uv pip install -e . --system
      - name: Run article content scraper
        run: python article_content_scraper.py
      - name: Commit results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/article-content/
          if ! git diff --staged --quiet; then
            COMMIT_MSG="Update article content - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git commit -m "$COMMIT_MSG"
            git push
          else
            echo 'No changes to commit.'
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
